import type { Metadata } from "next";
// import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";

import { QueryProvider } from "@/lib/query-client";

import "./globals.css";

// const space_grotesk = Space_Grotesk({
//   variable: "--font-space-grotesk",
//   subsets: ["latin"],
// });

const sfProDisplay = localFont({
  variable: "--font-sf-pro-display",
  src: [
    {
      path: "./fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Solvro Web Template",
  description: "Generated by create next app with solvro config",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${sfProDisplay.variable} font-sans antialiased`}>
          {children}
        </body>
      </QueryProvider>
    </html>
  );
}
